[package]
name = "adventofcode-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
gxhash = "3.4.1"
smol_str = "0.3.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name="adventofcode-benchmark"
harness = false
